### PR TITLE
fix a critical mistake in my_lib_cuda_kernel.cu

### PR DESCRIPTION
**Pull request by lim0606**
I made a critical mistake in my_lib_cuda_kernel.cu, and fixed it.

I apologize for my mistake! 

Best, 

Jae Hyun Lim

### CODE REVIEW

**Comment by fxia22** [comment]
merged, thanks

**Comment by fxia22** [comment]
@jj0mst This needs to be done, the reason for the performance drop is likely due to how you handle out of FOV? Also, you can play with the learning rates of STN, they are known to be difficult to train.

**Comment by jj0mst** [comment]
I don't use the entire network, but only the bilinear sampler.

I have sampling grids at different scales as output of a part of my network (which is not related to stn), so i just use the bilinear sampler for sampling from an input image.

Since there's no learnable parameter in the portion i use, i ran some simple tests to check that it does what i need and everything seems correct.

I just wanted to be sure that this change was correct.

Thank you both for your work.

**Comment by fxia22** [comment]
@jj0mst your use case is similar to mine, I did similar tests and things seem to work fine. Thanks for your feedback.

**Pull request merged**
